version: '3'
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

#  web:
#     build: .
#     env_file:
#       - .env
#     volumes:
#       - .:/myapp
#     ports:
#       - 3000:3000
#     depends_on:
#       - db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 5050:80

volumes:
  pgadmin:
  db:
